### PR TITLE
integrated filter database into document flow

### PR DESCRIPTION
**Pull request by AveryVine**
This does several things:

- Added better exception handling around missing SERVICE_ACCOUNT_KEYs
- Slight refactoring of various database methods for better readability and consistency
- Improved Javadocs for consistency
- Added filter collection to the flow of documents from outside sources

More on the last point: now, when a document is to be added to the database, it is first added to the filter collection. Once this collection fills up (100 is the current maximum) or a long enough time period elapses (1 minute is the current maximum), the entirety of the filter collection is copied over to the master collection. In the future, document cleaning will occur during this step.

### CODE REVIEW

**Review by maxim-kuzmenko — COMMENTED** [review]
Good stuff

**Comment by AveryVine** [comment]
@lifeofcows 
*comments on changes*
*doesn't review pull request*
*can't merge*

**Review by JKirkYuan — APPROVED** [review]
Should split into more PRs next time. There's a lot of code that might get missed during review 💯

**Comment by AveryVine** [comment]
Duly noted

**Pull request merged**
